name: Dataset generation

on:
  push:
    branches:
      - master

  # TODO: should be triggered on issue creation or comments added?
  #schedule: # every day
  #  - cron:  '0 8 * * *'

jobs:
  generate-dataset:
    runs-on: ubuntu-latest
    container: 
        image: alext234/datascience:latest

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
            pip install -r requirements.txt

      - name: Extract urls and labels
        run: |
            TOKEN=${{ secrets.GITHUB_TOKEN }} jupyter nbconvert --execute notebooks/generate-label-urls.ipynb  --ExecutePreprocessor.timeout=600 --debug
            ls

      - name: Download images from urls
        run: |
            jupyter nbconvert --execute notebooks/download-images.ipynb  --ExecutePreprocessor.timeout=1200 --debug
            ls

      - name: zip up and upload
        env:
            KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
            KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
        run: |
            cd notebooks && zip dataset.zip -r weed not_weed
            mkdir kaggle
            cd kaggle
            kaggle datasets metadata superdatabot/weeds-not-weeds 
            mv ../dataset.zip .
            kaggle datasets version -m "update from Github Action Run ID $GITHUB_RUN_ID"
            
            
