name: Dataset generation

on:
  push:
    branches:
      - master

  # TODO: should be triggered on issue creation or comments added?
  #schedule: # every day
  #  - cron:  '0 8 * * *'

jobs:
  generate-dataset:
    runs-on: ubuntu-latest
    container: 
        image: alext234/datascience:latest

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
            pip install -r requirements.txt

      - name: Extract urls and labels
        run: |
            TOKEN=${{ secrets.GITHUB_TOKEN }} jupyter nbconvert --execute notebooks/generate-datasets.ipynb  --ExecutePreprocessor.timeout=600 --debug

      - name: Download images from urls
        run: |
            ls notebooks
